# Generated by Django 3.2.5 on 2021-09-05 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0002_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='railwaycomment',
            name='post',
        ),
    ]
