# Generated by Django 3.2.5 on 2021-09-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0003_remove_railwaycomment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='defencecomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='indianarmycomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='policecomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='ssccomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='statescomment',
            name='post',
        ),
    ]
