# Generated by Django 3.2.5 on 2021-09-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0005_remove_jobsdata_eligiblity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificationdata',
            name='eligiblity',
        ),
        migrations.RemoveField(
            model_name='otherdata',
            name='eligiblity',
        ),
        migrations.RemoveField(
            model_name='schoolunidata',
            name='eligiblity',
        ),
    ]
