# Generated by Django 3.2.5 on 2021-09-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0007_topmarquee'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmarquee',
            name='category10',
            field=models.CharField(choices=[('jobs', 'Latest Jobs'), ('admitcard', 'Admit Card'), ('govtplan', 'Sarkari Yojnaye'), ('result', 'Result'), ('answerkey', 'Answer Key'), ('syllabus', 'Syllabus'), ('schooluni', 'School/University'), ('certification', 'Certification'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='category11',
            field=models.CharField(choices=[('jobs', 'Latest Jobs'), ('admitcard', 'Admit Card'), ('govtplan', 'Sarkari Yojnaye'), ('result', 'Result'), ('answerkey', 'Answer Key'), ('syllabus', 'Syllabus'), ('schooluni', 'School/University'), ('certification', 'Certification'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='category12',
            field=models.CharField(choices=[('jobs', 'Latest Jobs'), ('admitcard', 'Admit Card'), ('govtplan', 'Sarkari Yojnaye'), ('result', 'Result'), ('answerkey', 'Answer Key'), ('syllabus', 'Syllabus'), ('schooluni', 'School/University'), ('certification', 'Certification'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='category5',
            field=models.CharField(choices=[('jobs', 'Latest Jobs'), ('admitcard', 'Admit Card'), ('govtplan', 'Sarkari Yojnaye'), ('result', 'Result'), ('answerkey', 'Answer Key'), ('syllabus', 'Syllabus'), ('schooluni', 'School/University'), ('certification', 'Certification'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='category6',
            field=models.CharField(choices=[('jobs', 'Latest Jobs'), ('admitcard', 'Admit Card'), ('govtplan', 'Sarkari Yojnaye'), ('result', 'Result'), ('answerkey', 'Answer Key'), ('syllabus', 'Syllabus'), ('schooluni', 'School/University'), ('certification', 'Certification'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='category7',
            field=models.CharField(choices=[('jobs', 'Latest Jobs'), ('admitcard', 'Admit Card'), ('govtplan', 'Sarkari Yojnaye'), ('result', 'Result'), ('answerkey', 'Answer Key'), ('syllabus', 'Syllabus'), ('schooluni', 'School/University'), ('certification', 'Certification'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='category8',
            field=models.CharField(choices=[('jobs', 'Latest Jobs'), ('admitcard', 'Admit Card'), ('govtplan', 'Sarkari Yojnaye'), ('result', 'Result'), ('answerkey', 'Answer Key'), ('syllabus', 'Syllabus'), ('schooluni', 'School/University'), ('certification', 'Certification'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='category9',
            field=models.CharField(choices=[('jobs', 'Latest Jobs'), ('admitcard', 'Admit Card'), ('govtplan', 'Sarkari Yojnaye'), ('result', 'Result'), ('answerkey', 'Answer Key'), ('syllabus', 'Syllabus'), ('schooluni', 'School/University'), ('certification', 'Certification'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='post_name10',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='post_name11',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='post_name12',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='post_name5',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='post_name6',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='post_name7',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='post_name8',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='post_name9',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='slug10',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='slug11',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='slug12',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='slug5',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='slug6',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='slug7',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='slug8',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='slug9',
            field=models.CharField(default='', max_length=600),
        ),
    ]
