# Generated by Django 3.2.5 on 2021-09-06 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0008_auto_20210905_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPaper',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('thehindu', 'THE HINDU'), ('indianexpress', 'INDIAN EXPRESS'), ('hindustantimes', 'HINDUSTAN TIMES')], default='', max_length=400)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('news_link', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
