# Generated by Django 3.2.5 on 2021-09-06 13:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0010_alter_newspaper_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPaperComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mygovernmentjobs.newspapercomment')),
            ],
        ),
    ]
