# Generated by Django 3.2.5 on 2021-09-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0013_auto_20210907_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewc', models.IntegerField(default=0)),
            ],
        ),
    ]
