# Generated by Django 3.2.5 on 2021-09-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0014_indexcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitcarddata',
            name='viewc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answerkeydata',
            name='viewc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bank',
            name='viewc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificationdata',
            name='viewc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='defence',
            name='viewc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='governmentplan',
            name='viewc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indianarmy',
            name='viewc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobsdata',
            name='viewc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='viewc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='otherdata',
            name='viewc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='police',
            name='viewc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='railway',
            name='viewc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resultdata',
            name='viewc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schoolunidata',
            name='viewc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ssc',
            name='viewc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='state',
            name='viewc',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syllabusdata',
            name='viewc',
            field=models.IntegerField(default=0),
        ),
    ]
