# Generated by Django 3.2.5 on 2021-09-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0016_auto_20210912_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCompressor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imagecomp', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
