# Generated by Django 3.2.5 on 2021-09-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0017_imagecompressor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecompressor',
            name='name',
        ),
    ]
