# Generated by Django 3.2.5 on 2021-09-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0018_remove_imagecompressor_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageCompressor',
        ),
    ]
