# Generated by Django 3.2.7 on 2021-09-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0019_delete_imagecompressor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousYearPaper',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(choices=[('ntpc', 'RRB NTPC'), ('groupd', 'RRB Group D'), ('locopilot', 'RRB Loco Pilot'), ('rjunior', 'RRB Junior Engineer'), ('rother', 'RRB Other'), ('cgl', 'SSC CGL'), ('gd', 'SSC GD'), ('stenographer', 'SSC Stenographer'), ('mts', 'SSC MTS'), ('cpo', 'SSC CPO'), ('sscgraduate', 'SSC Graduate Lavel'), ('chsl', 'SSC CHSL'), ('sother', 'SSC Other'), ('cds', 'Defence CDS'), ('indiannavy', 'Defence Indian Navy'), ('indianairforce', 'Defence Indian Air Force'), ('dother', 'Defence Other'), ('allbank', 'Bank'), ('uppolice', 'UP Police'), ('hrpolice', 'Haryana Police'), ('delhipolice', 'Delhi Police'), ('biharpolice', 'Bihar Police'), ('upstate', 'Up State'), ('hrstate', 'Haryana State'), ('delhistate', 'Delhi State'), ('biharstate', 'Bihar State')], max_length=100)),
                ('name', models.CharField(default='', max_length=400)),
                ('link', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
