# Generated by Django 3.2.7 on 2021-09-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0020_previousyearpaper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='registration_coice',
            new_name='registration_choice',
        ),
        migrations.RenameField(
            model_name='certificationdata',
            old_name='result_coice',
            new_name='result_choice',
        ),
        migrations.RenameField(
            model_name='diploma',
            old_name='registration_coice',
            new_name='registration_choice',
        ),
        migrations.RenameField(
            model_name='governmentplan',
            old_name='registration_coice',
            new_name='registration_choice',
        ),
        migrations.RenameField(
            model_name='jobsdata',
            old_name='registration_coice',
            new_name='registration_choice',
        ),
        migrations.RenameField(
            model_name='otherdata',
            old_name='registration_coice',
            new_name='registration_choice',
        ),
        migrations.RenameField(
            model_name='privatejobs',
            old_name='registration_coice',
            new_name='registration_choice',
        ),
        migrations.RenameField(
            model_name='schoolunidata',
            old_name='registration_coice',
            new_name='registration_choice',
        ),
        migrations.AddField(
            model_name='admission',
            name='applytitle',
            field=models.CharField(default='Registration', max_length=100),
        ),
        migrations.AddField(
            model_name='certificationdata',
            name='applytitle',
            field=models.CharField(default='Registration', max_length=100),
        ),
        migrations.AddField(
            model_name='diploma',
            name='applytitle',
            field=models.CharField(default='Registration', max_length=100),
        ),
        migrations.AddField(
            model_name='governmentplan',
            name='applytitle',
            field=models.CharField(default='Registration', max_length=100),
        ),
        migrations.AddField(
            model_name='jobsdata',
            name='applytitle',
            field=models.CharField(default='Registration', max_length=100),
        ),
        migrations.AddField(
            model_name='otherdata',
            name='applytitle',
            field=models.CharField(default='Registration', max_length=100),
        ),
        migrations.AddField(
            model_name='privatejobs',
            name='applytitle',
            field=models.CharField(default='Registration', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolunidata',
            name='applytitle',
            field=models.CharField(default='Registration', max_length=100),
        ),
    ]
