# Generated by Django 3.2.7 on 2021-09-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0021_auto_20210913_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='gen_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='admission',
            name='obc_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='admission',
            name='scst_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='certificationdata',
            name='gen_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='certificationdata',
            name='max_age',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='certificationdata',
            name='min_age',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='certificationdata',
            name='obc_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='certificationdata',
            name='scst_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=models.CharField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='gen_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='max_age',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='min_age',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='obc_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='scst_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='governmentplan',
            name='gen_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='governmentplan',
            name='obc_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='governmentplan',
            name='scst_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='gen_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='max_age',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='min_age',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='obc_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='scst_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='offlineform',
            name='gen_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='offlineform',
            name='max_age',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='offlineform',
            name='min_age',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='offlineform',
            name='obc_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='offlineform',
            name='scst_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='gen_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='max_age',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='min_age',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='obc_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='scst_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='privatejobs',
            name='gen_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='privatejobs',
            name='max_age',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='privatejobs',
            name='min_age',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='privatejobs',
            name='obc_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='privatejobs',
            name='scst_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='schoolunidata',
            name='gen_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='schoolunidata',
            name='max_age',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='schoolunidata',
            name='min_age',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='schoolunidata',
            name='obc_fees',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='schoolunidata',
            name='scst_fees',
            field=models.CharField(default='', max_length=400),
        ),
    ]
