# Generated by Django 3.2.7 on 2021-09-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0022_auto_20210913_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admitcardtitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='downloadcertificatetitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='resulttitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='admission',
            name='syllabustitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='admitcarddata',
            name='admitcardtitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='answerkeydata',
            name='answerkeytitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='certificationdata',
            name='admitcardtitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='certificationdata',
            name='answerkeytitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='certificationdata',
            name='correctiontitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='certificationdata',
            name='downloadcertificatetitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='certificationdata',
            name='resulttitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='diploma',
            name='admitcardtitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='diploma',
            name='downloadcertificatetitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='diploma',
            name='resulttitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='diploma',
            name='syllabustitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='offlineform',
            name='syllabustitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='privatejobs',
            name='admitcardtitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='privatejobs',
            name='downloadcertificatetitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='privatejobs',
            name='resulttitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='privatejobs',
            name='syllabustitle',
            field=models.CharField(default='Click here', max_length=100),
        ),
        migrations.AddField(
            model_name='resultdata',
            name='resulttitle',
            field=models.CharField(default='Registration', max_length=100),
        ),
        migrations.AddField(
            model_name='syllabusdata',
            name='syllabustitle',
            field=models.CharField(default='Registration', max_length=100),
        ),
        migrations.AlterField(
            model_name='admission',
            name='plan_complete',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='admission',
            name='plan_date_begin',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='admission',
            name='plan_last_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='admitcarddata',
            name='admit_card_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='answerkeydata',
            name='post_date_update',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificationdata',
            name='admit_card_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificationdata',
            name='age_on_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificationdata',
            name='app_begin_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificationdata',
            name='complete_last_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificationdata',
            name='exam_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificationdata',
            name='last_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='certificationdata',
            name='pay_examination_fees',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='age_on_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='plan_complete',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='plan_date_begin',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='plan_last_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='governmentplan',
            name='plan_complete',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='governmentplan',
            name='plan_date_begin',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='governmentplan',
            name='plan_last_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='admit_card_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='age_on_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='app_begin_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='complete_last_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='exam_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='last_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='pay_examination_fees',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='offlineform',
            name='age_on_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='offlineform',
            name='plan_complete',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='offlineform',
            name='plan_date_begin',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='offlineform',
            name='plan_last_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='admit_card_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='age_on_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='app_begin_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='complete_last_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='exam_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='last_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='pay_examination_fees',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='privatejobs',
            name='age_on_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='privatejobs',
            name='plan_complete',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='privatejobs',
            name='plan_date_begin',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='privatejobs',
            name='plan_last_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resultdata',
            name='post_date_update',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolunidata',
            name='admit_card_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolunidata',
            name='age_on_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolunidata',
            name='app_begin_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolunidata',
            name='complete_last_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolunidata',
            name='exam_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolunidata',
            name='last_date',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='schoolunidata',
            name='pay_examination_fees',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='syllabusdata',
            name='post_date_update',
            field=models.CharField(default='', max_length=200),
        ),
    ]
