# Generated by Django 3.2.7 on 2021-09-14 02:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0023_auto_20210913_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='category',
            field=models.CharField(choices=[('THE_HINDU', 'THE HINDU'), ('TIMES_OF_INDIA', 'TIMES OF INDIA'), ('HINDUSTAN_TIMES', 'HINDUSTAN TIMES'), ('AMAR_UJALA', 'AMAR UJALA'), ('DAINIK_JAGRAN', 'DAINIK JAGRAN')], default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='resultdata',
            name='resulttitle',
            field=models.CharField(default='Click', max_length=100),
        ),
        migrations.AlterField(
            model_name='syllabusdata',
            name='syllabustitle',
            field=models.CharField(default='Click', max_length=100),
        ),
        migrations.CreateModel(
            name='PreviousComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mygovernmentjobs.previouscomment')),
            ],
        ),
    ]
