# Generated by Django 3.2.7 on 2021-09-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0025_auto_20210914_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='plan_info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='certificationdata',
            name='post_information',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='plan_info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='governmentplan',
            name='plan_info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='post_information',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='offlineform',
            name='plan_info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='post_information',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='privatejobs',
            name='plan_info',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='schoolunidata',
            name='post_information',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
