# Generated by Django 3.2.7 on 2021-09-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0026_auto_20210914_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultdata',
            name='post_date_update',
            field=models.CharField(default='', max_length=800),
        ),
    ]
