# Generated by Django 3.2.7 on 2021-09-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0027_alter_resultdata_post_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitcarddata',
            name='admit_card_date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
