# Generated by Django 3.2.7 on 2021-09-14 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0028_alter_admitcarddata_admit_card_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitcarddata',
            name='admit_card_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='resultdata',
            name='post_date_update',
            field=models.DateField(blank=True),
        ),
    ]
