# Generated by Django 3.2.7 on 2021-09-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0029_auto_20210914_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitcarddata',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='admitcarddata',
            name='post_detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='admitcarddata',
            name='post_information',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='admitcarddata',
            name='post_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='answerkeydata',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='answerkeydata',
            name='post_detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='answerkeydata',
            name='post_information',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='answerkeydata',
            name='post_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='resultdata',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resultdata',
            name='post_detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resultdata',
            name='post_information',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='resultdata',
            name='post_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='syllabusdata',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='syllabusdata',
            name='post_detail',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='syllabusdata',
            name='post_information',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='syllabusdata',
            name='post_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='answerkeydata',
            name='post_date_update',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='resultdata',
            name='post_date_update',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='syllabusdata',
            name='post_date_update',
            field=models.DateTimeField(),
        ),
    ]
