# Generated by Django 3.2.7 on 2021-09-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0030_auto_20210914_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admitcarddata',
            name='admit_card_date',
        ),
    ]
