# Generated by Django 3.2.7 on 2021-09-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0031_remove_admitcarddata_admit_card_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='admitcarddata',
            name='admit_card_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
