# Generated by Django 3.2.7 on 2021-09-15 08:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0033_alter_admitcarddata_admit_card_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamMaterial',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(choices=[('currentaffairs', 'Current Affairs'), ('gk', 'Gk'), ('math', 'Math'), ('advancemath', 'Advance Math'), ('savidhan', 'Bhartiya Savidhan'), ('hindi', 'Hindi'), ('english', 'English'), ('reasoning', 'Reasoning'), ('ccc', 'CCC'), ('geography', 'Geography'), ('history', 'Indian History'), ('economy', 'Indian Economy'), ('science', 'Science'), ('other', 'Other'), ('computer', 'Computer'), ('allbook', 'All Book')], max_length=100)),
                ('name', models.CharField(default='', max_length=400)),
                ('size', models.CharField(default='', max_length=10)),
                ('image', models.ImageField(default='', upload_to='media/')),
                ('link', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='previousyearpaper',
            name='image',
            field=models.ImageField(default='', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='previousyearpaper',
            name='size',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='ExamMaterialComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mygovernmentjobs.exammaterialcomment')),
            ],
        ),
    ]
