# Generated by Django 3.2.7 on 2021-09-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0034_auto_20210915_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topmarquee',
            name='category1',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='category10',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='category11',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='category12',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='category2',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='category3',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='category4',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='category5',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='category6',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='category7',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='category8',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='category9',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='slug1',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='slug10',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='slug11',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='slug12',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='slug2',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='slug3',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='slug4',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='slug5',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='slug6',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='slug7',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='slug8',
        ),
        migrations.RemoveField(
            model_name='topmarquee',
            name='slug9',
        ),
        migrations.RemoveField(
            model_name='toppost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='toppost',
            name='slug',
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='link1',
            field=models.CharField(default='/', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='link10',
            field=models.CharField(default='/', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='link11',
            field=models.CharField(default='/', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='link12',
            field=models.CharField(default='/', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='link2',
            field=models.CharField(default='/', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='link3',
            field=models.CharField(default='/', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='link4',
            field=models.CharField(default='/', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='link5',
            field=models.CharField(default='/', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='link6',
            field=models.CharField(default='/', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='link7',
            field=models.CharField(default='/', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='link8',
            field=models.CharField(default='/', max_length=600),
        ),
        migrations.AddField(
            model_name='topmarquee',
            name='link9',
            field=models.CharField(default='/', max_length=600),
        ),
        migrations.AddField(
            model_name='toppost',
            name='link',
            field=models.CharField(default='/', max_length=600),
        ),
    ]
