# Generated by Django 3.2.5 on 2021-11-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygovernmentjobs', '0035_auto_20210917_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitcarddata',
            name='post_date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='answerkeydata',
            name='post_date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='certificationdata',
            name='post_date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='post_date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='otherdata',
            name='post_date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='resultdata',
            name='post_date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='schoolunidata',
            name='post_date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='syllabusdata',
            name='post_date_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
